networks:
  dev:
    driver: bridge

services:
  app-db:
    container_name: docker-joseph-db
    build:
      dockerfile: Dockerfile.db
    ports:
      - "5464:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: